#! /bin/sh

# Clean lingering programs when reloaded
$HOME/.config/bspwm/clean.sh &

pgrep -x sxhkd > /dev/null || sxhkd &

# Fix Mouse cursor on startup 
xsetroot -cursor_name left_ptr

# Monitor Config
bspc monitor -d I II III IV V VI VII VIII IX X

# BSPWM Config
bspc config border_width         0
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config presel_feedback_color	      "#202020"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Firefox-esr desktop='^2' follow=on
bspc rule -a Org.gnome.Nautilus desktop='^4' follow=on
bspc rule -a wine desktop='^5' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a celluloid state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

polybar mainbar &
pgrep -x picom > /dev/null || picom 2>/dev/null &

feh --bg-fill /home/subin/.wallpaper/wallpaper1.jpg
